Inc13
zavyalov-den/url-shortener pull request #13
Opened 2022-03-31 13:11 UTC by zavyalov-den

13й инкремент.
Есть проблема с прохождением 13го инкремента. Локально все работает. Actions в гигхабе зависают при выполнении тестов
![Screenshot from 2022-03-31 16-08-31](https://user-images.githubusercontent.com/54071585/161062492-152a585a-780f-459d-9416-98dc66a7a3fc.png)
![Screenshot from 2022-03-31 16-05-29](https://user-images.githubusercontent.com/54071585/161062498-c22aec4f-cd04-40f1-9397-e4c97e10bcee.png)
.

2022-04-03 14:17 UTC, blattaria7 commented on internal/middlewares/auth.go
> +func RandomToken(n int) string {
Этот метод нигде не используется, для чего он нужен?

2022-04-03 14:18 UTC, blattaria7 commented on internal/storage/storage.go
> +	defer tx.Rollback(ctx)
метод tx.Rollback() возвращает ошибку, стоит ее проверять)

2022-04-03 14:29 UTC, blattaria7 commented on internal/handler/get_test.go
> +		db.SaveURL(1, storage.UserURL{
этот метод возвращает ошибку, хорошо бы ее инициализировать и проверить что ее нету. так как игнорирование ошибок в го - антипаттерн

я бы разрезолвила это так:
1. убрала бы данный конструктор
2. инициализировала бы в структуре тест-кейса переменную `notEmpty bool`
3. в описании каждого тест кейса писала бы необходимое мне значение в этой переменной
3. внутри теста уже, когда мы перебираем каждый тест-кейс, инициализировала бы сторадж и проверяла бы это условие
4. и в условии бы проверяла отсутствие ошибки:
```go
if ts.notEmpty {
		err := db.SaveURL(1, storage.UserURL{
			ShortURL:    service.ShortToURL("e9db20b2"),
			OriginalURL: "",
		})
		assert.NoError(t, err)
}
```

2022-04-03 14:32 UTC, blattaria7 commented on internal/storage/storage.go
> +	var result []BatchResponse
если мы можем предположить каким будет размер массива, стоит задавать ему размер при инициализации, дабы поберечь память) сейчас это не так критично, но точно пригодится в будущем )

а тут он равен размеру b, тк result увеличивается с каждой итерацией цикла )

2022-04-03 14:34 UTC, blattaria7 commented on internal/storage/storage.go
> +var ConflictError = errors.New("db: insert conflict occurred")
в го принято называть свои типы ошибок с `Err`, нужно переименовать на `ErrConflict`)

2022-04-03 14:36 UTC, blattaria7 commented on internal/storage/storage.go
> +			return fmt.Errorf("select from urls failed: %s", err)
для ошибок используем `%w`)

2022-04-03 16:30 UTC, blattaria7 commented on internal/storage/storage.go
> +	rows, err := d.db.Query(ctx, query, id)
`defer rows.Close` надо обязательно добавить

https://pkg.go.dev/database/sql#Rows.Close

2022-04-03 19:19 UTC, blattaria7 requested changes
К сожалению, не могу принять работу, так как не проходят тесты(

Что нужно сделать:
* Исправить ошибки из логов go vet test
* По 2 инкременту - необходимо добавить тестов в код
* Посмотреть логи в инкрементах, там кажется что-то лишнее пишется (например, в 10 тест проходит, но в STDOUT выводится http: named cookie not present)
* Поправить мои комментарии в MR

2022-04-04 12:45 UTC, zavyalov-den commented
Исправил замечания. 2й инкремент проходит, 13й так же зависает, но при локальной проверке - все работает в соответствии с ТЗ.

2022-04-04 12:53 UTC, zavyalov-den commented on internal/storage/storage.go
> +	var result []BatchResponse
тип []BatchResponse соответствует возвращаемому типу.
конструкцию в духе var result [len(b)]BatchResponse не пропускает компилятор, т.к. хочет, чтобы значение len(b) было известно на этапе компиляции.

да и []BatchResponse и [int]BatchResponse - разные типы. Нужно будет тогда приводить одно к другому, например как result[:]

2022-04-06 14:57 UTC, blattaria7 approved these changes

2022-04-19 08:19 UTC, merged